name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: "ubuntu-22.04"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: "1.21"

      - name: Build
        run: docker build . -t ghcr.io/jsirianni/pgbouncer_exporter:latest

      - name: Tag
        run: |
          docker tag \
            "ghcr.io/jsirianni/pgbouncer_exporter:latest" \
            "ghcr.io/jsirianni/pgbouncer_exporter:${{ github.ref }}"
      
      - name: Push
        run: |
          docker push \
            "ghcr.io/jsirianni/pgbouncer_exporter:latest"
          docker push \
            "ghcr.io/jsirianni/pgbouncer_exporter:${{ github.ref }}"
